import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Lora } from "next/font/google";


const inter = Inter({ 
  subsets: ["latin"],
  variable: "--font-inter"
});
const lora = Lora({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-lora"
})


export const metadata: Metadata = {
  title: "Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {


  return (
    <html lang="en">
      <body className={`${lora.variable} ${inter.className} antialiased`}>{children}</body>
    </html>
  );
}
